[package]
name = "dizi"
version = "0.1.0"
authors = ["Jeff Zhao <jeff.no.zhao@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "dizi-server"
path = "src/server/main.rs"

[[bin]]
name = "dizi"
path = "src/client/main.rs"

[dependencies]
alphanumeric-sort = "^1"
chrono = "^0"
cpal = { features = [ "jack" ], version = "^0" }
crossbeam = "^0"
dirs-next = "^2"
dizi_lib = { path = "lib/dizi_lib", version = "^0" }
globset = "^0"
libc = "^0"
lazy_static = "^1"
pipewire = { optional = true, version = "^0" }
rand = "^0"
rodio = { features = [ "symphonia-all" ], git = "https://github.com/RustAudio/rodio.git", version = "^0" }
rustyline = "^4"
serde = "^1"
serde_derive = "^1"
serde_json = "^1"
shell-words = "^1"
shellexpand = "^2"
signal-hook = "^0"
skim = "^0"
structopt = "^0"
termion = "^1"
toml = "^0"
tui = "^0"
unicode-width = "^0"
unicode-segmentation = "^1"
uuid = { features = [ "v4" ], version = "^0" }
xdg = "^2"

[features]
default = []
pipewire-all = [ "pipewire" ]
