[client]
socket = "/tmp/dizi-server-socket"

home_dir = "~/music"

[client.display]
show_borders = true
show_hidden = false

[client.display.sort]
reverse = false
sort_method = "natural"

[client.display.layout]
